name: sampleapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_easyloading: ^3.0.5
  get_storage: ^2.0.3
  flutter_secure_storage: ^8.0.0
  dio: ^4.0.6
  intl: ^0.18.0
  http: ^0.13.5
  custom_navigator:
    git:
      url: https://github.com/kjawadDeveloper/Custom-navigator.git

  proste_bezier_curve: ^2.0.2

  flutter_svg: ^1.1.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

